export const mockRooms = [
  {
    id: "00000000-0000-0000-0000-000000000001",
    name: "D'Lux Homes — Tower 4 Grass Residences",
    description: "Cozy 1-bedroom unit with balcony and city view at Tower 4 Grass Residences. Perfect for couples, families, or solo travelers. Comes with a complimentary welcome pack and everything you need for a relaxing staycation.",
    size: "1 Bedroom",
    bedType: "1 Full Double Bed + 1 Single Pull-Out Bed",
    floor: "Tower 4, Grass Residences",
    tower: "Grass Residences",
    location: "Tower 4 Grass Residences, SM North EDSA, Quezon City",
    capacity: 4,
    rating: 4.9,
    reviewCount: 48,
    price10hr: 1499,
    price10hrWeekend: 1799,
    price21hr: 1899,
    price21hrWeekend: 2099,
    additionalPaxFee: 300,
    basePax: 2,
    maxPax: 4,
    images: [
      "/images/rooms/1.jpg",
      "/images/rooms/2.jpg",
      "/images/rooms/3.jpg",
      "/images/rooms/4.jpg",
      "/images/rooms/5.jpg",
      "/images/rooms/6.jpg",
      "/images/rooms/7.jpg",
      "/images/rooms/8.jpg",
      "/images/rooms/10.jpg",
    ],
    amenities: [
      "Free WiFi",
      "Air Conditioning",
      "Smart TV",
      "Balcony",
      "Private Bathroom",
      "Microwave",
      "Refrigerator",
      "Kitchenette",
    ],
    welcomePack: [
      "Dental Kit",
      "Shampoo",
      "Bath Soap",
      "Drinking Water",
      "Use of Towels",
    ],
    inclusions: [
      "Microwave",
      "Refrigerator",
      "Tableware & cookware (light cooking)",
      "1 Full Double size bed",
      "1 Single Pull-Out Bed",
      "WiFi Unlimited Fibre",
      "Smart TV (Netflix & YouTube)",
      "Air conditioning",
      "Cold/Hot Shower & Bidet",
      "Board Games",
      "Videoke",
    ],
    amenityFees: [
      { name: "Swimming Pool", fee: "₱150/pax" },
      { name: "Basketball Court", fee: "₱150/pax" },
      { name: "Gym", fee: "₱150/pax" },
      { name: "Kids Playground", fee: "FREE" },
    ],
    parking: "₱350–₱500 for 22 hours (arrangements available)",
    nearby: [
      "Laundry Service",
      "Alfamart",
      "Smoking Area",
      "SM North EDSA",
      "Trinoma Ayala Mall",
      "SM North Sky Dome",
      "Quezon City Science High School",
      "Our Lady of Hope Parish Church",
      "Banks & ATMs",
    ],
    houseRules: [
      "Strictly NO Smoking / Vaping",
      "No Pets Allowed",
      "Not Accepting Walk-ins",
    ],
    stayTypes: ["10-Hour", "21-Hour"],
    blockedDates: [
      { date: "2026-04-18", type: "booked" },
      { date: "2026-04-19", type: "booked" },
      { date: "2026-04-20", type: "maintenance" },
      { date: "2026-04-25", type: "booked" },
      { date: "2026-04-26", type: "maintenance" },
      { date: "2026-05-01", type: "booked" },
      { date: "2026-05-02", type: "booked" },
      { date: "2026-05-03", type: "maintenance" },
    ],
  },
];

export const mockBookings = [
  {
    id: "BK1711234567",
    roomId: "1",
    roomName: "Azure Haven Suite",
    checkIn: "2026-04-05",
    checkOut: "2026-04-05",
    stayType: "21-Hour",
    guests: { adults: 2, children: 0, infants: 0 },
    status: "confirmed",
    totalAmount: 5500,
    addOns: [{ name: "Pool Pass", qty: 2, price: 100 }, { name: "Towels", qty: 2, price: 50 }],
    createdAt: "2026-03-28",
  },
  {
    id: "BK1711234568",
    roomId: "2",
    roomName: "Pearl Executive Room",
    checkIn: "2026-03-20",
    checkOut: "2026-03-20",
    stayType: "10-Hour",
    guests: { adults: 1, children: 0, infants: 0 },
    status: "checked-out",
    totalAmount: 2800,
    addOns: [],
    createdAt: "2026-03-18",
  },
  {
    id: "BK1711234569",
    roomId: "3",
    roomName: "Emerald Deluxe Studio",
    checkIn: "2026-04-15",
    checkOut: "2026-04-15",
    stayType: "6-Hour",
    guests: { adults: 2, children: 1, infants: 0 },
    status: "pending",
    totalAmount: 3075,
    addOns: [{ name: "Guest Kit", qty: 1, price: 75 }],
    createdAt: "2026-03-27",
  },
];

export const mockReviews = [
  { id: "1", author: "Jonathan Bantoc", rating: 5, comment: "Truly a great place to relax. The location is perfect for the couple and group of friends. It gives you a very relaxing ambience escape from the stressful situations because of the very cold temperature room. The swimming pool was so great. The owners were very accommodating and responsive. Highly recommended!", date: "2025-05-16", avatar: "JB" },
  { id: "2", author: "Donna Marie Osorio", rating: 5, comment: "This will be a little bit late for a reco, ..but anyways. Thank you so much D'Lux Homes .. A very aesthetic vibes room to enjoy! .. Thank you for having us here to celebrate my birthday! .. Thank you also for the very fast response esp. in terms of inquiry. ..onto our next staycation with you!!", date: "2025-03-03", avatar: "DO" },
  { id: "3", author: "Raechelle Angel", rating: 5, comment: "5 star\nThe place is comfortable and clean, the owner is friendly nag-enjoy kami ng family ko", date: "2024-05-12", avatar: "RA" },
  { id: "4", author: "Carlo Mendoza", rating: 5, comment: "Loved every minute of our stay. The pool pass was totally worth it!", date: "2026-01-20", avatar: "CM" },
];

export const mockAdminBookings = [
  { id: "BK1711234570", guest: "Maria Santos", room: "Azure Haven Suite", checkIn: "2026-03-29", stayType: "21-Hour", amount: 5700, status: "pending", email: "maria@example.com" },
  { id: "BK1711234571", guest: "Jose Reyes", room: "Pearl Executive Room", checkIn: "2026-03-30", stayType: "10-Hour", amount: 2800, status: "confirmed", email: "jose@example.com" },
  { id: "BK1711234572", guest: "Ana Cruz", room: "Emerald Deluxe Studio", checkIn: "2026-03-28", stayType: "6-Hour", amount: 3000, status: "checked-in", email: "ana@example.com" },
  { id: "BK1711234573", guest: "Carlo Mendoza", room: "Sapphire Corner Suite", checkIn: "2026-03-27", stayType: "21-Hour", amount: 8000, status: "checked-out", email: "carlo@example.com" },
  { id: "BK1711234574", guest: "Lucia Gomez", room: "Ruby Standard Room", checkIn: "2026-03-25", stayType: "6-Hour", amount: 1500, status: "rejected", email: "lucia@example.com" },
  { id: "BK1711234575", guest: "Pedro Lim", room: "Topaz Family Suite", checkIn: "2026-04-01", stayType: "21-Hour", amount: 9075, status: "pending", email: "pedro@example.com" },
];
